baseurl      = "https://www.harrisoncook.net"
title        = "Harrison Cook"
languageCode = "en-nz"
theme        = "hello-friend-ng"
paginate     = 10

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

# [markup.goldmark.renderer]
  # unsafe= true

[author]
  name = "Harrison Cook"

[params]
  dateform        = "2 Jan, 2006"
  dateformShort   = "2 Jan"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Subtitle for home
  homeSubtitle = "Software Engineer | Football Referee"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Metadata mostly used in document's head
  description = "Harrison Cook's Personal Website"
  keywords = "homepage, blog"
  images = [""]

  # Default theme "light" or "dark"
  enableThemeToggle = true
  defaultTheme = "dark"
  themeColor = "#252627"

  customCSS = ["css/all-pages.css"]
  customJS  = []

  # Social icons
  [[params.social]]
    name = "email"
    url  = "mailto:harrisoncook4+website@gmail.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/Fellsmarch"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/harrison-cook-33766653/"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Harrison Cook"
    # subtitle = ""
    keywords = ""
    # copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "C:\\Users\\Harrison>"
      logoHomeLink = "/"
    #   logoCursorDisabled = false
      logoCursorColor = "#8f34eb"
    #   logoCursorAnimate  = "2s"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

# Nav bar items
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "/posts"

  [[menu.main]]
    identifier = "about"
    name       = "Who?"
    url        = "/about"

  # [[menu.main]]
  #   identifier = "resume"
  #   name       = "Resume"
  #   url        = "/resume"

  [[menu.main]]
    identifier = "referee"
    name       = "Referee"
    url        = "/referee"

